import type { NotificationEventDefinition } from "../types/notifications.types";

type EventSeed = Omit<
  NotificationEventDefinition,
  "semanticIdentityContract" | "aggregatable"
>;
const event = (definition: EventSeed): Readonly<NotificationEventDefinition> =>
  Object.freeze({
    ...definition,
    semanticIdentityContract: "SOURCE_TYPE_SOURCE_ID_TRANSITION_ID",
    aggregatable: false,
  });
const billing = (seed: Omit<EventSeed, "category" | "recipientPolicy">) =>
  event({
    ...seed,
    category: "BILLING_SUBSCRIPTION",
    recipientPolicy: "OWNER_FINANCE",
  });

export const NOTIFICATION_EVENT_REGISTRY = Object.freeze({
  "billing.subscription_payment_failed": billing({
    eventType: "billing.subscription_payment_failed",
    urgencyLevel: "CRITICAL",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "MANDATORY",
    deepLinkPath: "/brand/settings/billing?action=dunning",
    title: "Subscription payment failed",
  }),
  "billing.subscription_payment_recovered": billing({
    eventType: "billing.subscription_payment_recovered",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    deepLinkPath: "/brand/settings/billing?focus=plan",
    title: "Subscription payment recovered",
  }),
  "billing.trial_expired": billing({
    eventType: "billing.trial_expired",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "MANDATORY",
    deepLinkPath: "/brand/settings/billing?view=pricing_matrix",
    title: "Trial expired",
  }),
  "billing.subscription_halted": billing({
    eventType: "billing.subscription_halted",
    urgencyLevel: "CRITICAL",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "MANDATORY",
    deepLinkPath: "/brand/settings/billing?action=update_payment",
    title: "Subscription halted",
  }),
  "billing.cancellation_scheduled": billing({
    eventType: "billing.cancellation_scheduled",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "MANDATORY",
    deepLinkPath: "/brand/settings/billing?focus=plan",
    title: "Cancellation scheduled",
  }),
  "billing.cancellation_effective": billing({
    eventType: "billing.cancellation_effective",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "MANDATORY",
    deepLinkPath: "/brand/settings/billing?focus=plan",
    title: "Cancellation effective",
  }),
  "billing.cancellation_reactivated": billing({
    eventType: "billing.cancellation_reactivated",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "MANDATORY",
    deepLinkPath: "/brand/settings/billing?focus=plan",
    title: "Subscription reactivated",
  }),
  "billing.invoice_ready": billing({
    eventType: "billing.invoice_ready",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    deepLinkPath: "/brand/settings/billing?focus=invoices",
    title: "Invoice ready",
  }),
  "escrow.funding_credited": event({
    eventType: "escrow.funding_credited",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE",
    deepLinkPath: "/brand/payouts",
    title: "Escrow funding credited",
  }),
  "escrow.collaboration_awaiting_funds": event({
    eventType: "escrow.collaboration_awaiting_funds",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/collaborations/{collaboration_id}",
    title: "Collaboration awaiting funds",
  }),
  "escrow.collaboration_refunded": event({
    eventType: "escrow.collaboration_refunded",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/collaborations/{collaboration_id}",
    title: "Collaboration funds refunded",
  }),
  "escrow.creator_payout_action_required": event({
    eventType: "escrow.creator_payout_action_required",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/payouts?obligation=payout-obligation:{obligation_id}",
    title: "Creator payout action required",
  }),
  "escrow.creator_payout_settled": event({
    eventType: "escrow.creator_payout_settled",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/payouts?obligation=payout-obligation:{obligation_id}",
    title: "Creator payout settled",
  }),
  "escrow.creator_payout_reversed": event({
    eventType: "escrow.creator_payout_reversed",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/payouts?obligation=payout-obligation:{obligation_id}",
    title: "Creator payout reversed",
  }),
  "escrow.brand_return_action_required": event({
    eventType: "escrow.brand_return_action_required",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE",
    deepLinkPath:
      "/brand/payouts?brand_return=brand-return:{brand_return_request_id}",
    title: "Brand return requires action",
  }),
  "escrow.brand_return_partial": event({
    eventType: "escrow.brand_return_partial",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE",
    deepLinkPath:
      "/brand/payouts?brand_return=brand-return:{brand_return_request_id}",
    title: "Brand return partially completed",
  }),
  "escrow.brand_return_completed": event({
    eventType: "escrow.brand_return_completed",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE",
    deepLinkPath:
      "/brand/payouts?brand_return=brand-return:{brand_return_request_id}",
    title: "Brand return completed",
  }),
  "payouts.reserve_approval_required": event({
    eventType: "payouts.reserve_approval_required",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE",
    deepLinkPath: "/brand/payouts",
    title: "Financial reserve approval required",
  }),
  "payouts.creator_setup_blocking": event({
    eventType: "payouts.creator_setup_blocking",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/payouts?obligation=payout-obligation:{obligation_id}",
    title: "Creator setup is blocking payment",
  }),
  "payouts.provider_action_required": event({
    eventType: "payouts.provider_action_required",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/payouts?obligation=payout-obligation:{obligation_id}",
    title: "Payment action required",
  }),
  "payouts.transfer_failed_or_reconciliation_required": event({
    eventType: "payouts.transfer_failed_or_reconciliation_required",
    category: "ESCROW_PAYOUTS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_FINANCE_PLUS_ACTIVE_TRIGGERING_CM",
    deepLinkPath: "/brand/payouts?obligation=payout-obligation:{obligation_id}",
    title: "Creator payment requires review",
  }),
  "campaigns.application_received": event({
    eventType: "campaigns.application_received",
    category: "CAMPAIGNS_APPLICATIONS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_CAMPAIGN_MANAGERS",
    deepLinkPath: "/brand/campaigns/{campaign_id}/applications",
    title: "Campaign application received",
  }),
  "collaborations.media_submitted_for_review": event({
    eventType: "collaborations.media_submitted_for_review",
    category: "COLLABORATIONS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_CAMPAIGN_MANAGERS",
    deepLinkPath: "/brand/collaborations/{collaboration_id}",
    title: "Media submitted for review",
  }),
  "intelligence.execution_completed": event({
    eventType: "intelligence.execution_completed",
    category: "BRAND_INTELLIGENCE",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "YES",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_CAMPAIGN_MANAGERS",
    deepLinkPath: "/brand/intelligence",
    title: "Brand Intelligence execution completed",
  }),
  "intelligence.execution_failed": event({
    eventType: "intelligence.execution_failed",
    category: "BRAND_INTELLIGENCE",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_CAMPAIGN_MANAGERS",
    deepLinkPath: "/brand/intelligence",
    title: "Brand Intelligence execution failed",
  }),
  "team.member_access_revoked": event({
    eventType: "team.member_access_revoked",
    category: "TEAM_ACCOUNT_INTEGRATIONS",
    urgencyLevel: "INFORMATIONAL",
    actionable: false,
    inAppPolicy: "NONE",
    emailPolicy: "MANDATORY",
    recipientPolicy: "AFFECTED_USER_EMAIL_ONLY",
    deepLinkPath: "/",
    title: "Brand workspace access revoked",
  }),
  "integration.instagram_token_expired": event({
    eventType: "integration.instagram_token_expired",
    category: "TEAM_ACCOUNT_INTEGRATIONS",
    urgencyLevel: "ACTION_REQUIRED",
    actionable: true,
    inAppPolicy: "REQUIRED",
    emailPolicy: "OPTIONAL",
    recipientPolicy: "OWNER_CAMPAIGN_MANAGERS",
    deepLinkPath: "/brand/settings/integrations?state=token_error",
    title: "Instagram connection expired",
  }),
} satisfies Record<string, Readonly<NotificationEventDefinition>>);

export function getEventDefinition(
  eventType: string,
): Readonly<NotificationEventDefinition> | null {
  return (
    NOTIFICATION_EVENT_REGISTRY[
      eventType as keyof typeof NOTIFICATION_EVENT_REGISTRY
    ] ?? null
  );
}
export function resolveDeepLinkPath(
  template: string,
  payload: Record<string, unknown>,
): string {
  return template.replace(/\{(\w+)\}/g, (_match, key: string) =>
    payload[key] == null ? "" : String(payload[key]),
  );
}
