export const BRAND_HOME_SECTION_IDS = [
  "NEEDS_ATTENTION",
  "CREATOR_SHOP_HAS_LEARNED",
  "OPPORTUNITIES_NEXT_ACTIONS",
  "CURRENT_MOMENTUM",
] as const;

export const BRAND_HOME_PRIORITY_TIERS = [
  "BLOCKED_FAILED_ACTION_REQUIRED",
  "DEADLINE_SLA_TIME_SENSITIVE",
  "MATERIAL_SETUP_CAPABILITY_BLOCKER",
  "MATERIAL_OPPORTUNITY",
  "NEW_OR_CHANGED_INTELLIGENCE",
  "MEANINGFUL_MOMENTUM",
] as const;

export const BRAND_HOME_SOURCE_DOMAINS = [
  "BRAND",
  "WORKSPACE_READINESS",
  "PROVIDER_READINESS",
  "COLLABORATION",
  "BRAND_INTELLIGENCE",
  "OFFERING",
  "PRODUCT_INTELLIGENCE",
  "CAMPAIGN",
] as const;

export const BRAND_HOME_ITEM_KINDS = [
  "COLLABORATION_ATTENTION",
  "COLLABORATION_MOMENTUM",
  "WORKSPACE_SETUP",
  "PROVIDER_RECOVERY",
  "BRAND_INTELLIGENCE_LEARNED",
  "PRODUCT_INTELLIGENCE_LEARNED",
  "OFFERING_OPPORTUNITY",
  "CAMPAIGN_MOMENTUM",
] as const;

export const BRAND_HOME_NAVIGATION_DESTINATIONS = [
  "HOME",
  "BRAND_CENTRE",
  "OFFERINGS",
  "CAMPAIGNS",
  "COLLABORATIONS",
  "SETTINGS",
  "SETTINGS_INTEGRATIONS",
  "SETTINGS_BILLING",
] as const;

export type BrandHomeSectionId = (typeof BRAND_HOME_SECTION_IDS)[number];
export type BrandHomePriorityTier = (typeof BRAND_HOME_PRIORITY_TIERS)[number];
export type BrandHomeSourceDomain = (typeof BRAND_HOME_SOURCE_DOMAINS)[number];
