export const CREATOR_ENTRY_ERROR = {
  ACCOUNT_EXISTS_SIGN_IN_REQUIRED: "ACCOUNT_EXISTS_SIGN_IN_REQUIRED",
  ACCOUNT_CONTEXT_CONFLICT: "ACCOUNT_CONTEXT_CONFLICT",
  CREATOR_CONTEXT_RECOVERY_REQUIRED: "CREATOR_CONTEXT_RECOVERY_REQUIRED",
  EMAIL_VERIFICATION_INVALID_OR_EXPIRED:
    "EMAIL_VERIFICATION_INVALID_OR_EXPIRED",
  GOOGLE_IDENTITY_CONFLICT: "GOOGLE_IDENTITY_CONFLICT",
} as const;

export type CreatorEntryAccountContext =
  | "CREATOR_READY"
  | "ACCOUNT_CONTEXT_CONFLICT"
  | "CONTEXT_RECOVERY_REQUIRED";

export type CreatorEntryNextAction =
  | "SIGN_IN"
  | "VERIFY_EMAIL"
  | "CONNECT_INSTAGRAM"
  | "RESOLVE_ACCOUNT_CONTEXT"
  | "RECOVER_CREATOR_CONTEXT"
  | "CREATOR_WORKSPACE_ENTRY";
