export const CREATOR_ENTRY_ERROR = {
  ACCOUNT_EXISTS_SIGN_IN_REQUIRED: "ACCOUNT_EXISTS_SIGN_IN_REQUIRED",
  ACCOUNT_CONTEXT_CONFLICT: "ACCOUNT_CONTEXT_CONFLICT",
  CREATOR_CONTEXT_RECOVERY_REQUIRED: "CREATOR_CONTEXT_RECOVERY_REQUIRED",
  EMAIL_VERIFICATION_INVALID_OR_EXPIRED:
    "EMAIL_VERIFICATION_INVALID_OR_EXPIRED",
  GOOGLE_IDENTITY_CONFLICT: "GOOGLE_IDENTITY_CONFLICT",
  INSTAGRAM_AUTHORIZATION_DENIED: "INSTAGRAM_AUTHORIZATION_DENIED",
  INSTAGRAM_AUTHORIZATION_STALE: "INSTAGRAM_AUTHORIZATION_STALE",
  INSTAGRAM_IDENTITY_CONFLICT: "INSTAGRAM_IDENTITY_CONFLICT",
  INSTAGRAM_IDENTITY_ALREADY_IN_USE: "INSTAGRAM_IDENTITY_ALREADY_IN_USE",
  INSTAGRAM_NOT_CONNECTED: "INSTAGRAM_NOT_CONNECTED",
  INSTAGRAM_PROFESSIONAL_ACCOUNT_REQUIRED:
    "INSTAGRAM_PROFESSIONAL_ACCOUNT_REQUIRED",
  INSTAGRAM_PROFESSIONAL_ACCOUNT_REVALIDATION_REQUIRED:
    "INSTAGRAM_PROFESSIONAL_ACCOUNT_REVALIDATION_REQUIRED",
  INSTAGRAM_PROVIDER_RETRY_REQUIRED: "INSTAGRAM_PROVIDER_RETRY_REQUIRED",
  INSTAGRAM_RECOVERY_FLOW_REQUIRED: "INSTAGRAM_RECOVERY_FLOW_REQUIRED",
  INSTAGRAM_RECONNECT_REQUIRED: "INSTAGRAM_RECONNECT_REQUIRED",
  PROVIDER_ACCESS_BLOCKED: "PROVIDER_ACCESS_BLOCKED",
  CREATOR_PLATFORM_ACCESS_REQUIRED: "CREATOR_PLATFORM_ACCESS_REQUIRED",
  CREATOR_ENTRY_CONTINUATION_NOT_FOUND: "CREATOR_ENTRY_CONTINUATION_NOT_FOUND",
  CREATOR_ENTRY_CONTINUATION_EXPIRED: "CREATOR_ENTRY_CONTINUATION_EXPIRED",
  CREATOR_ENTRY_CONTINUATION_IDENTITY_CONFLICT:
    "CREATOR_ENTRY_CONTINUATION_IDENTITY_CONFLICT",
} as const;

export type CreatorEntryAccountContext =
  | "CREATOR_READY"
  | "ACCOUNT_CONTEXT_CONFLICT"
  | "CONTEXT_RECOVERY_REQUIRED";

export type CreatorEntryNextAction =
  | "SIGN_IN"
  | "VERIFY_EMAIL"
  | "CONNECT_INSTAGRAM"
  | "RECONNECT_INSTAGRAM"
  | "REVALIDATE_INSTAGRAM"
  | "RESOLVE_ACCOUNT_CONTEXT"
  | "RECOVER_CREATOR_CONTEXT"
  | "CREATOR_WORKSPACE_ENTRY"
  | "RETURN_TO_ORIGINATING_CAMPAIGN";
