// GENERATED from frozen current-read authority. No processor execution registration.
export const CURRENT_READ_AUTHORITY =
  "a6bed1f28564c002f7d76931de0b4dd960ea5ae1";
export const READ_ONLY_OBJECT_CONTRACTS = [
  {
    objectSemanticId: "differentiation_and_proof",
    outputContractId: "brand_differentiation_output_contract",
    outputContractVersion: "1.0",
    ownedPathPatterns: [
      "$",
      "$/i/{semantic_id}",
      "$/i/{semantic_id}/f/differentiator",
      "$/i/{semantic_id}/f/proof_points",
      "$/i/{semantic_id}/f/proof_points/i/{semantic_id}",
      "$/i/{semantic_id}/f/proof_points/i/{semantic_id}/f/statement",
    ],
    requiredMaterializedPaths: ["$"],
    authorityPath:
      "intelligence/engines/brand_intelligence/branches/brand_expression/artifacts/brand_differentiation/output_contract.yaml",
    authoritySha256:
      "f8eff7bb3599d6ca9f89a5e5e5b5879a8077d773829a16de5b37f2adf98da7fa",
  },
  {
    objectSemanticId: "audience_personas",
    outputContractId: "audience_persona_synthesis_output_contract",
    outputContractVersion: "1.0",
    ownedPathPatterns: [
      "$",
      "$/i/{semantic_id}",
      "$/i/{semantic_id}/f/barriers_or_concerns",
      "$/i/{semantic_id}/f/barriers_or_concerns/i/{semantic_id}",
      "$/i/{semantic_id}/f/barriers_or_concerns/i/{semantic_id}/f/value",
      "$/i/{semantic_id}/f/creator_communication_implications",
      "$/i/{semantic_id}/f/creator_communication_implications/i/{semantic_id}",
      "$/i/{semantic_id}/f/creator_communication_implications/i/{semantic_id}/f/value",
      "$/i/{semantic_id}/f/demographic_context",
      "$/i/{semantic_id}/f/geography_context",
      "$/i/{semantic_id}/f/key_characteristics",
      "$/i/{semantic_id}/f/key_characteristics/i/{semantic_id}",
      "$/i/{semantic_id}/f/key_characteristics/i/{semantic_id}/f/value",
      "$/i/{semantic_id}/f/label",
      "$/i/{semantic_id}/f/lifecycle",
      "$/i/{semantic_id}/f/motivations",
      "$/i/{semantic_id}/f/motivations/i/{semantic_id}",
      "$/i/{semantic_id}/f/motivations/i/{semantic_id}/f/value",
      "$/i/{semantic_id}/f/summary",
      "$/i/{semantic_id}/f/trust_credibility_needs",
      "$/i/{semantic_id}/f/trust_credibility_needs/i/{semantic_id}",
      "$/i/{semantic_id}/f/trust_credibility_needs/i/{semantic_id}/f/value",
    ],
    requiredMaterializedPaths: ["$"],
    authorityPath:
      "intelligence/engines/brand_intelligence/branches/audience/artifacts/audience_persona_synthesis/output_contract.yaml",
    authoritySha256:
      "581013669d641d9b4a9a369cc108cdde86fadd473eaabb24e0a636d9de5d62ec",
  },
  {
    objectSemanticId: "visual_style_profile",
    outputContractId: "visual_style_synthesis_output_contract",
    outputContractVersion: "1.0",
    ownedPathPatterns: [
      "$",
      "$/f/graphic_treatment",
      "$/f/graphic_treatment/f/traits",
      "$/f/graphic_treatment/f/traits/i/{semantic_id}",
      "$/f/graphic_treatment/f/traits/i/{semantic_id}/f/value",
      "$/f/imagery_style",
      "$/f/imagery_style/f/mood_or_treatment",
      "$/f/imagery_style/f/mood_or_treatment/i/{semantic_id}",
      "$/f/imagery_style/f/mood_or_treatment/i/{semantic_id}/f/value",
      "$/f/imagery_style/f/photographic_tendencies",
      "$/f/imagery_style/f/photographic_tendencies/i/{semantic_id}",
      "$/f/imagery_style/f/photographic_tendencies/i/{semantic_id}/f/value",
      "$/f/imagery_style/f/subject_tendencies",
      "$/f/imagery_style/f/subject_tendencies/i/{semantic_id}",
      "$/f/imagery_style/f/subject_tendencies/i/{semantic_id}/f/value",
      "$/f/style_traits",
      "$/f/style_traits/i/{semantic_id}",
      "$/f/style_traits/i/{semantic_id}/f/trait",
      "$/f/summary",
      "$/f/visual_constraints",
      "$/f/visual_constraints/i/{semantic_id}",
      "$/f/visual_constraints/i/{semantic_id}/f/rule",
    ],
    requiredMaterializedPaths: ["$"],
    authorityPath:
      "intelligence/engines/brand_intelligence/branches/visual_identity/artifacts/visual_style_synthesis/output_contract.yaml",
    authoritySha256:
      "f76fa3d9f974774e6e715bda0d0a407ee9813d0ab4992bdef9ed044b3d2bed90",
  },
  {
    objectSemanticId: "serviceability_profile",
    outputContractId: "serviceability_synthesis_output_contract",
    outputContractVersion: "1.0",
    ownedPathPatterns: [
      "$",
      "$/f/coverage_is_heterogeneous",
      "$/f/mixed_coverage_note",
      "$/f/overall_scope",
      "$/f/serviceability_basis",
      "$/f/serviceability_basis/i/{semantic_id}",
      "$/f/serviceability_basis/i/{semantic_id}/f/applies_to_market_refs",
      "$/f/serviceability_basis/i/{semantic_id}/f/basis_type",
      "$/f/serviceability_basis/i/{semantic_id}/f/business_state_refs",
      "$/f/serviceability_basis/i/{semantic_id}/f/evidence_refs",
      "$/f/serviceability_basis/i/{semantic_id}/f/offering_refs",
      "$/f/serviceable_markets",
      "$/f/serviceable_markets/i/{semantic_id}",
      "$/f/serviceable_markets/i/{semantic_id}/f/country_code",
      "$/f/serviceable_markets/i/{semantic_id}/f/label",
      "$/f/serviceable_markets/i/{semantic_id}/f/locality",
      "$/f/serviceable_markets/i/{semantic_id}/f/radius_km",
      "$/f/serviceable_markets/i/{semantic_id}/f/region",
      "$/f/serviceable_markets/i/{semantic_id}/f/scope",
    ],
    requiredMaterializedPaths: ["$"],
    authorityPath:
      "intelligence/engines/brand_intelligence/branches/serviceability/artifacts/serviceability_synthesis/output_contract.yaml",
    authoritySha256:
      "3c31d643afc32fae90271623a7418f29a56afd6646147f3021facdb549efcd74",
  },
] as const;
