import type { ChatCapabilityDescriptor } from "./chat-capability.contract";
import {
  CampaignChatCapabilityInputSchema,
  CollaborationChatCapabilityInputSchema,
  EmptyChatCapabilityInputSchema,
  NavigateChatCapabilityInputSchema,
  OfferingChatCapabilityInputSchema,
} from "./chat-capability.schema";
import {
  BrandCurrentCapabilityOutputSchema,
  CampaignListCapabilityOutputSchema,
  CampaignReadCapabilityOutputSchema,
  CollaborationListCapabilityOutputSchema,
  CollaborationReadCapabilityOutputSchema,
  IntelligenceCapabilityOutputSchema,
  NavigateCapabilityOutputSchema,
  OfferingListCapabilityOutputSchema,
  OfferingReadCapabilityOutputSchema,
  ProviderReadinessCapabilityOutputSchema,
  WorkspaceReadinessCapabilityOutputSchema,
  WorkspaceContextCapabilityOutputSchema,
} from "./chat-capability-output.schema";

export const CHAT_FIRST_SLICE_CAPABILITY_IDS = [
  "workspace.context.read",
  "brand.current.read",
  "offering.list",
  "offering.read",
  "brand_intelligence.current.read",
  "product_intelligence.current.read",
  "campaign.list",
  "campaign.read",
  "collaboration.list",
  "collaboration.read",
  "workspace.readiness.read",
  "provider.readiness.read",
  "app.navigate",
] as const;

const implemented = (
  id: (typeof CHAT_FIRST_SLICE_CAPABILITY_IDS)[number],
  capabilityClass: "READ" | "NAVIGATE",
  domain: string,
  inputSchema: ChatCapabilityDescriptor["inputSchema"],
  outputSchema: NonNullable<ChatCapabilityDescriptor["outputSchema"]>,
): ChatCapabilityDescriptor => ({
  id,
  class: capabilityClass,
  owner: "chat-home",
  domain,
  risk: "NON_CONSEQUENTIAL",
  confirmation: "NOT_REQUIRED",
  inputSchema,
  outputSchema,
  implementationState: "IMPLEMENTED",
  availability: "AVAILABLE",
});

export const CHAT_CAPABILITY_CATALOG: readonly ChatCapabilityDescriptor[] = [
  implemented(
    "workspace.context.read",
    "READ",
    "workspace",
    EmptyChatCapabilityInputSchema,
    WorkspaceContextCapabilityOutputSchema,
  ),
  implemented(
    "brand.current.read",
    "READ",
    "brand",
    EmptyChatCapabilityInputSchema,
    BrandCurrentCapabilityOutputSchema,
  ),
  implemented(
    "offering.list",
    "READ",
    "offering",
    EmptyChatCapabilityInputSchema,
    OfferingListCapabilityOutputSchema,
  ),
  implemented(
    "offering.read",
    "READ",
    "offering",
    OfferingChatCapabilityInputSchema,
    OfferingReadCapabilityOutputSchema,
  ),
  implemented(
    "brand_intelligence.current.read",
    "READ",
    "brand-intelligence",
    EmptyChatCapabilityInputSchema,
    IntelligenceCapabilityOutputSchema,
  ),
  implemented(
    "product_intelligence.current.read",
    "READ",
    "product-intelligence",
    OfferingChatCapabilityInputSchema,
    IntelligenceCapabilityOutputSchema,
  ),
  implemented(
    "campaign.list",
    "READ",
    "campaign",
    EmptyChatCapabilityInputSchema,
    CampaignListCapabilityOutputSchema,
  ),
  implemented(
    "campaign.read",
    "READ",
    "campaign",
    CampaignChatCapabilityInputSchema,
    CampaignReadCapabilityOutputSchema,
  ),
  implemented(
    "collaboration.list",
    "READ",
    "collaboration",
    EmptyChatCapabilityInputSchema,
    CollaborationListCapabilityOutputSchema,
  ),
  implemented(
    "collaboration.read",
    "READ",
    "collaboration",
    CollaborationChatCapabilityInputSchema,
    CollaborationReadCapabilityOutputSchema,
  ),
  implemented(
    "workspace.readiness.read",
    "READ",
    "workspace-readiness",
    EmptyChatCapabilityInputSchema,
    WorkspaceReadinessCapabilityOutputSchema,
  ),
  implemented(
    "provider.readiness.read",
    "READ",
    "provider-readiness",
    EmptyChatCapabilityInputSchema,
    ProviderReadinessCapabilityOutputSchema,
  ),
  implemented(
    "app.navigate",
    "NAVIGATE",
    "navigation",
    NavigateChatCapabilityInputSchema,
    NavigateCapabilityOutputSchema,
  ),
];
