export const CREATOR_HOME_KPI_IDS = [
  "AVAILABLE_CAMPAIGNS",
  "APPLICATIONS_IN_PROGRESS",
  "ACTIVE_COLLABORATIONS",
  "UNREAD_UPDATES",
] as const;

export const CREATOR_HOME_SECTION_IDS = [
  "NEEDS_YOUR_ATTENTION",
  "YOUR_WORK",
  "CAMPAIGNS_AVAILABLE",
  "RECENT_ACTIVITY",
] as const;

export const CREATOR_HOME_QUICK_ACTION_IDS = [
  "BROWSE_CAMPAIGNS",
  "MY_APPLICATIONS",
  "COLLABORATIONS",
  "SETTINGS",
] as const;

export const CREATOR_HOME_SOURCE_DOMAINS = [
  "SETTINGS",
  "OPPORTUNITIES",
  "APPLICATIONS",
  "COLLABORATIONS",
  "NOTIFICATIONS",
] as const;

export const CREATOR_HOME_DESTINATIONS = [
  "CREATOR_CAMPAIGNS",
  "CREATOR_OPPORTUNITY_DETAIL",
  "CREATOR_APPLICATIONS",
  "CREATOR_APPLICATION_DETAIL",
  "CREATOR_COLLABORATIONS",
  "CREATOR_COLLABORATION_THREAD",
  "CREATOR_SETTINGS",
  "CREATOR_SETTINGS_INSTAGRAM",
] as const;

export type CreatorHomeSourceDomain =
  (typeof CREATOR_HOME_SOURCE_DOMAINS)[number];
export type CreatorHomeSectionId = (typeof CREATOR_HOME_SECTION_IDS)[number];
